/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.naomod.ecore2xcore;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'fr.naomod.ecore2xcore.greeting' plugin.
 */
class Ecore2xcoreGradlePluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("io.github.ATL-Research.ecore2xcore");

        // Verify the result
        assertNotNull(project.getTasks().findByName("generateXcore"));
    }
}
